version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Init submodules
          command: git submodule update --init --recursive
      - run:
          name: Install pygraphviz
          command: sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run not-slow tests
          command: poetry run pytest -m "not slow" --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      # Commenting out because the slow tests are much too slow (> 3 hours)
      # - run:
      #     name: Run slow tests
      #     command: poetry run pytest -s -m "slow" --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Init submodules
          command: git submodule update --init --recursive
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build Docker image
          command: docker build . -t ghcr.io/alignmentresearch/acdc
      - run:
          name: Publish Docker image
          command: |
            echo "${GHCR_DOCKER_TOKEN}" | docker login --username "${GHCR_DOCKER_USER}" --password-stdin
            docker push ghcr.io/alignmentresearch/acdc

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - test
          context:
            # these are defined in the Organization Settings in the Web App, see https://app.circleci.com/settings/organization/github/AlignmentResearch/contexts
            - ghcr-auth
